language: php

php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"

script: "./vendor/bin/tester tests/ -p php -c ./tests/php-unix.ini -j 1"

before_script:
    - composer self-update
    - composer install --dev --prefer-source
